### PR TITLE
Use libui for gralloc on devices without legacy gralloc HAL

### PR DESCRIPTION
**Pull request by NotKit**
On some Android 11 devices that shipped with gralloc 4 (for example, device with MediaTek SoCs) there is no gralloc HAL library anymore that can be loaded through libhybris.

This PR tries to implement similar thing to what libhwc2_compat_layer does via libui as that has abstraction over multiple gralloc versions and communicates with gralloc allocator service via HIDL, while still loading the mapper library inside the process.

### CODE REVIEW

**Comment by mlehtima** [comment]
This seems to fail to build on some older android bases. On android 5 base I got "ui.c:21:10: fatal error: android/rect.h: No such file or directory"

**Comment by NotKit** [comment]
Should be fixed now, tested to still compile for motorola-titan with Android 5.1.

**Review by krnlyng — APPROVED** [review]

**Comment by mlehtima** [comment]
When building this I get
`gralloc.c: In function 'hybris_gralloc_initialize':
gralloc.c:156:13: warning: implicit declaration of function 'hybris_ui_initialize'; did you mean 'hybris_gralloc_initialize'? [-Wimplicit-function-declaration]
             hybris_ui_initialize();
             ^~~~~~~~~~~~~~~~~~~~
             hybris_gralloc_initialize
gralloc.c:157:17: warning: implicit declaration of function 'hybris_ui_check_for_symbol' [-Wimplicit-function-declaration]
             if (hybris_ui_check_for_symbol("graphic_buffer_allocator_allocate")) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by krnlyng** [comment]
Can you fix those? Thanks

**Review by mlehtima — APPROVED** [review]

**Pull request merged**
