### PR TITLE
hybris: Only unload the wsmod when the last user of it is gone.

### PR DESCRIPTION
**Pull request by krnlyng**

### CODE REVIEW

**Review by mlehtima — APPROVED** [review]

**Comment by krnlyng** [comment]
@fredldotme Since you've done the changes for hot swapping the ws, does this change affect you negatively in any way? In theory i think hot swapping should still work this way, but it would be good to know if it does in practice.

**Comment by fredldotme** [comment]
> @fredldotme Since you've done the changes for hot swapping the ws, does this change affect you negatively in any way? In theory i think hot swapping should still work this way, but it would be good to know if it does in practice.

This change makes `eglinfo` from the `graphics-test-tools` Snap work very much what one expects, with no known downside.
Various EGL platforms, where libhybris implements 2, get loaded and probed in sequence and unloaded again before the next one is attempted.
Previously it would crash at the second EGL platform as one is already loaded and giving unexpected results.

**Comment by fredldotme** [comment]
Okay from what I've seen so far not unloading the WS in `ws_Terminate()` could indeed result in the `eglinfo` behavior to break again, unless the new WS gets to replace it at time of `eglInitialize()`. Still a little weird to keep the WS around until `eglInitialize()`.

**Comment by krnlyng** [comment]
> Okay from what I've seen so far not unloading the WS in `ws_Terminate()` could indeed result in the `eglinfo` behavior to break again, unless the new WS gets to replace it at time of `eglInitialize()`. Still a little weird to keep the WS around until `eglInitialize()`.

With these changes it should unload and load the new ws when it has actually changed in ws_init() which gets called from eglGetDisplay/eglGetPlatformDisplay (__eglHybrisGetPlatformDisplayCommon) unless the old ws is still in use (e.g. eglTerminate not yet called).

The reason for doing it this way is that it's allowed to call eglInitialize after eglTerminate with the same display argument, see: https://registry.khronos.org/EGL/sdk/docs/man/html/eglTerminate.xhtml

**Comment by krnlyng** [comment]
Also in the current state eglTerminate unconditionally unloads the ws. But with multiple threads going on there are still things that rely on the ws being loaded to be called and thus crash.

**Comment by krnlyng** [comment]
NOTE: Even if we would unload the ws in eglTerminate and reload it in eglInitialize this would not work properly since the display that was gotten via eglGetDisplay will be invalid as soon as the ws has been unloaded.

So it would be great to know if this pr does not break your usecase, if it does then i have to think of something else.

**Comment by fredldotme** [comment]
This looks good!

```
Android platform:
EGL API version: 1.4
EGL vendor string: Android
EGL version string: 1.4 Android META-EGL
EGL client APIs: OpenGL_ES
EGL extensions string:
    EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time
    EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer
    EGL_ANDROID_front_buffer_auto_refresh
    EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata
    EGL_EXT_surface_CTA861_3_metadata EGL_EXT_gl_colorspace_scrgb
    EGL_EXT_gl_colorspace_scrgb_linear
    EGL_EXT_gl_colorspace_display_p3_linear
    EGL_EXT_gl_colorspace_display_p3 EGL_EXT_gl_colorspace_bt2020_linear
    EGL_EXT_gl_colorspace_bt2020_pq EGL_KHR_image EGL_KHR_image_base
    EGL_EXT_image_gl_colorspace EGL_KHR_lock_surface
    EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync
    EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_surfaceless_context
    EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer
    EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update
    EGL_EXT_pixel_format_float EGL_KHR_create_context_no_error
    EGL_KHR_mutable_render_buffer EGL_EXT_yuv_surface
    EGL_EXT_protected_content EGL_IMG_context_priority
    EGL_KHR_no_config_context EGL_HYBRIS_native_buffer2
    EGL_HYBRIS_WL_acquire_native_buffer EGL_WL_bind_wayland_display
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
...

Wayland platform:
EGL API version: 1.4
EGL vendor string: Android
EGL version string: 1.4 Android META-EGL
EGL client APIs: OpenGL_ES
EGL extensions string:
    EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time
    EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer
    EGL_ANDROID_front_buffer_auto_refresh
    EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata
    EGL_EXT_surface_CTA861_3_metadata EGL_EXT_gl_colorspace_scrgb
    EGL_EXT_gl_colorspace_scrgb_linear
    EGL_EXT_gl_colorspace_display_p3_linear
    EGL_EXT_gl_colorspace_display_p3 EGL_EXT_gl_colorspace_bt2020_linear
    EGL_EXT_gl_colorspace_bt2020_pq EGL_KHR_image EGL_KHR_image_base
    EGL_EXT_image_gl_colorspace EGL_KHR_lock_surface
    EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_gl_renderbuffer_image EGL_KHR_reusable_sync
    EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_surfaceless_context
    EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer
    EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update
    EGL_EXT_pixel_format_float EGL_KHR_create_context_no_error
    EGL_KHR_mutable_render_buffer EGL_EXT_yuv_surface
    EGL_EXT_protected_content EGL_IMG_context_priority
    EGL_KHR_no_config_context EGL_HYBRIS_native_buffer2
    EGL_HYBRIS_WL_acquire_native_buffer EGL_WL_bind_wayland_display
    EGL_EXT_swap_buffers_with_damage
    EGL_WL_create_wayland_buffer_from_image
```

If it matters, it's a LGTM.

**Review by mlehtima — APPROVED** [review]

**Pull request merged**
