### PR TITLE
hybris: Use correct struct in glEGLImageTargetTexture2DOES of glesv2

### PR DESCRIPTION
**Pull request by rainemak**
See also egl.c

### CODE REVIEW

**Comment by rainemak** [comment]
@krnlyng @sledges review ?

**Comment by krnlyng** [comment]
LGTM

**Comment by krnlyng** [comment]
one moment: in GLESv1_CM this is not yet implemented. there are not many users of GLESv1_CM but we should fix it there too.

**Comment by rainemak** [comment]
Updated glesv1_cm.c

**Pull request merged**
