### PR TITLE
Import all changes from the Ubuntu fork

### PR DESCRIPTION
**Pull request by morphis**
This import nearly all changes we did in Ubuntu on top of a libhybris release from the end of last year. There are quite some differences but a lot of features added.

* Android 6 support
* Arm64 support
* Dynamic linker support
* A lot enablement changes

I didn't went through the list of other changes done in upstream but I feel the easiest is the apply any needed ones again on top of this giant merge proposal (if still needed).

### CODE REVIEW

**Comment by bhush9** [comment]
Trying to build this, seems to fail at configure stage..

```
configure.ac:224: error: required file 'camera/Makefile.in' not found
configure.ac:224: error: required file 'camera/libcamera.pc.in' not found
common/Makefile.am: installing './depcomp'
egl/platforms/common/Makefile.am:29: warning: '%'-style pattern rules are a GNU make extension
egl/platforms/common/Makefile.am:32: warning: '%'-style pattern rules are a GNU make extension
egl/platforms/common/Makefile.am:35: warning: '%'-style pattern rules are a GNU make extension
tests/Makefile.am:131: warning: variable 'test_sf_SOURCES' is defined but no program or
tests/Makefile.am:131: library has 'test_sf' as canonical name (possible typo)
tests/Makefile.am:123: warning: variable 'test_ui_SOURCES' is defined but no program or
tests/Makefile.am:123: library has 'test_ui' as canonical name (possible typo)
tests/Makefile.am:135: warning: variable 'test_sf_LDADD' is defined but no program or
tests/Makefile.am:135: library has 'test_sf' as canonical name (possible typo)
tests/Makefile.am:127: warning: variable 'test_ui_LDADD' is defined but no program or
tests/Makefile.am:127: library has 'test_ui' as canonical name (possible typo)
```

**Comment by morphis** [comment]
Fixed.

**Comment by krnlyng** [comment]
42e27f9d8dbfc8ae28460d744dfaa1baf008db1c is kinda hacky but much more nice than what i have done locally :+1: 

3ab2ca5039c5d1cf9fba62f39c5654a1db610edc needs to be thought about, can we build everything into libhybris-common and still select the linkers at runtime? probably would require us to rename most linker functions, or is there a saner way?

7ae2b395d136ac229015bf67c0d7d9dfc6011c67 can this be made with env variable HYBRIS_LINKER_STDOUT=1 like it was before?

is the packaging really necessary in this repository? i kind of liked the idea of having a generic repository + a packaging repository with a submodule.

can we have the tracing functionality as a debug option without adding a special hook for every symbol?
i am thinking about something like this (simplified and pseudocode):

compile time solution:
```
#ifdef DEBUG
... all the indirect hooks useful for tracing ...
#endif

#ifdef DEBUG
#define HOOK_DIRECT(symbol) {#symbol, _hybris_hook_##symbol}
#else
#define HOOK_DIRECT(symbol) {#symbol, symbol},
#endif

#define HOOK(symbol) {#symbol, _hybris_hook##symbol}
#define HOOK_TO(symbol, hook) {#symbol, hook}

struct _hook hooks[] = {
...
    HOOK_DIRECT(strcmp), // for functions that can be hooked directly
    HOOK(fgets), // for functions that cannot be directly hooked
    HOOK_TO(__progname, something_other_than__hybris_hook), // for variables
...
};
```

OR at runtime:

```
struct _hook hooks[] = {
...
    {"strcmp", strcmp},
...
};
struct _hook debug_hooks[] = {
...
    {"strcmp", _hybris_hook_
...
};
```

void *get_hooked_symbol(const char *symbol)
{
    if env variable HYBRIS_TRACE is set
        return symbol from debug_hooks;
    else
        return symbol from hooks;
}

thanks for adding the PR!

**Comment by morphis** [comment]
For https://github.com/libhybris/libhybris/commit/3ab2ca5039c5d1cf9fba62f39c5654a1db610edc I agree that this can be done better but we didn't found a good think when adding the dynamic linker in time to get things working well. With the indirect stuff libGLESv2 was crashing at multiple places. Everything else should be fine and working. Also could we make the dynamic linker an optional feature but that would make the test scenarios quite more complex.

For https://github.com/libhybris/libhybris/commit/7ae2b395d136ac229015bf67c0d7d9dfc6011c67 , sure we can add those env variables back to the mm linker. We didn't had the time yet to do that. Patches welcome :-)

For the hook/trace thing I like what you propose to do at runtime but actually this should be covered with some nice macros too.

**Comment by krnlyng** [comment]
@morphis seems like _hybris_hook_scandir and my_scandir are duplicates of each other
same for scandirat
alphasort, versionsort seem to be hooked twice too (there are more duplicate hooks)

**Comment by ghosalmartin** [comment]
With this version of the linker it seemed to crash inside is_gnu_hash for EGL libs.

**Comment by bhush9** [comment]
backtrace of test_hwcomposer for record

```
#0  soinfo::is_gnu_hash (this=this@entry=0x6c2f7369) at linker.cpp:2385
#1  0xf73bb154 in soinfo::find_symbol_by_name (this=this@entry=0x6c2f7369, symbol_name=..., vi=vi@entry=0x0, symbol=symbol@entry=0xfffef270) at linker.cpp:491
#2  0xf73bb4c0 in <lambda(soinfo*)>::operator() (current_soinfo=0x6c2f7369, __closure=0xfffef22c) at linker.cpp:938
#3  walk_dependencies_tree<dlsym_handle_lookup(soinfo*, soinfo*, soinfo**, SymbolName&)::<lambda(soinfo*)> >(soinfo **, <lambda(soinfo*)>, size_t) ( root_soinfos=root_soinfos@entry=0xfffef264, action=..., root_soinfos_size=1) at linker.cpp:912
#4  0xf73bbcce in dlsym_handle_lookup (symbol_name=..., found=0xfffef2b4, skip_until=0x0, root=0x6c2f7369) at linker.cpp:949
#5  dlsym_handle_lookup (si=si@entry=0x6c2f7369, found=found@entry=0xfffef2b4, name=name@entry=0xf7356695 "eglCreateStreamKHR") at linker.cpp:969
#6  0xf73b9596 in android_dlsym (handle=0x6c2f7369, symbol=0xf7356695 "eglCreateStreamKHR") at dlfcn.cpp:127
#7  0xf6696628 in ?? ()
```

**Comment by ghosalmartin** [comment]
@bhush9 Did the one from my fork still have the same issue?

**Comment by bhush9** [comment]
I am not super sure.. but I can retry in sometime.

**Comment by krnlyng** [comment]
@morphis we're still investigating the is_gnu_hash issue, but i have added some commits on top of this: https://github.com/krnlyng/libhybris/tree/ubuntu it works well on my device and solves a segfault on exit of all processes (e157e180905c4073f6278037f28653489512e120). please take a look.

**Comment by morphis** [comment]
@krnlyng You need to be careful with the linker you select on your platform. The hash scheme was changed with the Android 5 linker and if there are old binaries in your system things may conflict.

I didn't looked into the details of your changes yet but I would propose we merge this PR and then get your changes on top of this one as followup PRs. How does that sound?

**Comment by krnlyng** [comment]
@morphis we have selected the correct linker, the issue was due to a pthread_getspecific issue where it loaded a key which was not initialized which caused all kinds of confusion within the blobs

we're still looking into getting this to work on our devices, hybris-13 adaptation works fine now with some additional changes but we want to have it work on older adaptations too to make the transition as smooth (as in be ready with our pull requests as soon as this has been merged) as possible, also we're still unsure about the packaging inside this repository since it bloats the history unnecessarily with commits that are either not useful for us or for ubuntu. so yes it sounds good but we would appreciate if we waited a few days longer before merging this to sort things out.

have you seen my comment about the glesv2 issue?
also the bionic_file struct has a little issue which causes crashes in most applications (so far only seen on exit). it think it might be worth considering the inclusion of 7891cf24735aaac90c9006bc5cf5dd7bf8cfa3aa directly here.

thanks for the hard work!

**Comment by ghosalmartin** [comment]
So are we going with this version of libhybris android 6 changes? What needs to be done to ensure legacy platforms are well supported?

**Comment by morphis** [comment]
@ghosalmartin Yes we will. This PR gives support for different linker versions where the right one is selected at runtime. We still support the 4.x based linker for legacy platforms and will use the 6.x one for newer ones.

**Comment by ghosalmartin** [comment]
Awesome, so whats stopping us? :P

**Comment by morphis** [comment]
Let me drop the debian/ part of this and then I will merge this in.

**Comment by bhush9** [comment]
Oh reminds me, I had to edit extract-headers.h to extract some more header files to get it built actually. I think it was set_abort_message.h and one more file..

**Comment by morphis** [comment]
@bhush9 Can you submit those changes as an additional PR?

**Comment by bhush9** [comment]
Sure, I can do that.

**Comment by morphis** [comment]
As CI has approved this now I intend to merge this later today if nobody else comments.

**Comment by stskeeps** [comment]
go for it

**Pull request merged**
