### PR TITLE
WIP: initial android 8 support

### PR DESCRIPTION
**Pull request by krnlyng**
Needs testing for older adaptations, and different devices, please help out :).

Properties have been changed a bit, now the bionic implementation is used in android >=8 in order to avoid having to reimplement many of the property features which are now mandatory.

Gralloc1 is supported, HWC2 not yet, for testing surfaceflinger can be used, but HWC2 support will be added in the future.

### CODE REVIEW

**Comment by lyric999** [comment]
compile fail,error info:

make[2]: Leaving directory `/media/sns/libhybris-android8-initial/hybris/opencl'
Making all in utils
make[2]: Entering directory `/media/sns/libhybris-android8-initial/hybris/utils'
  CC       setprop-setprop.o
  CC       getprop-getprop.o
  CCLD     setprop
  CCLD     getprop
/home/sns/sns-cross-compilation/aarch64-sns_neon-linux-gnueabi/bin/../lib/gcc/aarch64-sns_neon-linux-gnueabi/5.2.0/../../../../aarch64-sns_neon-linux-gnueabi/bin/ld.bfd: warning: libhybris-common.so.1, needed by ../properties/.libs/libandroid-properties.so, not found (try using -rpath or -rpath-link)
../properties/.libs/libandroid-properties.so: undefined reference to `android_dlclose'
../properties/.libs/libandroid-properties.so: undefined reference to `android_dlsym'
../properties/.libs/libandroid-properties.so: undefined reference to `android_dlopen'
collect2: error: ld returned 1 exit status
make[2]: *** [setprop] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/sns/sns-cross-compilation/aarch64-sns_neon-linux-gnueabi/bin/../lib/gcc/aarch64-sns_neon-linux-gnueabi/5.2.0/../../../../aarch64-sns_neon-linux-gnueabi/bin/ld.bfd: warning: libhybris-common.so.1, needed by ../properties/.libs/libandroid-properties.so, not found (try using -rpath or -rpath-link)
../properties/.libs/libandroid-properties.so: undefined reference to `android_dlclose'
../properties/.libs/libandroid-properties.so: undefined reference to `android_dlsym'
../properties/.libs/libandroid-properties.so: undefined reference to `android_dlopen'
collect2: error: ld returned 1 exit status
make[2]: *** [getprop] Error 1

**Comment by krnlyng** [comment]
@lyric999 hey, that looks strange, i've checked the Makefile.am's and i currently cannot figure out how this can happen, is this a clean build? i can cleanly build this and @mlehtima has confirmed it works for him too.
do you have changes additionally to this?
are you sure there are no problems at an earlier stage in this build?
can you describe your build environment, including OS/tool versions and so on?

**Comment by Lyric1985** [comment]
My build steps:
1,./autogen.sh
2,./configure  --enable-adreno-quirks --enable-trace --enable-debug
--enable-arch=arm64 --enable-experimental --prefix=/usr/local/hybris
--with-default-egl-platform=fbdev
--with-android-headers=/home/sns/workspace/libhybris/android-8-1-0-headers
--host=aarch64-sns_neon-linux-gnueabi
--target=aarch64-sns_neon-linux-gnueabi
host_alias=aarch64-sns_neon-linux-gnueabi
target_alias=aarch64-sns_neon-linux-gnueabi
CC=aarch64-sns_neon-linux-gnueabi-gcc
'LDFLAGS=-L/home/sns/xorg/snshf64/usr/lib
-Wl,-rpath=/home/sns/xorg/snshf64/usr/lib'
CPPFLAGS=-I/home/sns/xorg/snshf64/usr/include
CXX=aarch64-sns_neon-linux-gnueabi-g++
PKG_CONFIG_PATH=/home/sns/xorg/snshf64/usr/lib/pkgconfig --no-create
--no-recursion
3,./config.status
4,make -j4

I didn't modify any code,after the clean build is still the same.The same
steps can be compiled without patching (use android6.0 header,do not
compile test).I use host ubuntu 14.04,gcc tool is support arm64 gcc.





2018-06-08 23:56 GMT+08:00 Franz-Josef Anton Friedrich Haider <
notifications@github.com>:

**Comment by lyric999** [comment]
When you do not call the android_dlopen and android_dlclose method, you can compile it. after I test on the Open-Q 820 Development Kit development board, a segfault occurs during the import of the libc++ library,info:
func:[call_function] [ Calling function @ 0x7f81b85028 for "/system/lib64/libc++.so" ]
Segmentation fault

How to locate this problem?

**Comment by krnlyng** [comment]
added WIP to the title since some things most likely need to be ironed out still.

**Comment by krnlyng** [comment]
we probably need to support the HIDL API for gralloc too.

**Comment by krnlyng** [comment]
moved to #407

**Pull request closed without merging**
