### PR TITLE
[WIP] introduce glesv3 wrapper

### PR DESCRIPTION
**Pull request by bhush9**
RFC, DONT MERGE YET.

This uses the scripts in utils to generate the wrapper.. Not quite sure how to test this yet.

### CODE REVIEW

**Comment by krnlyng** [comment]
Needs also adaptation in egl.c:

https://github.com/libhybris/libhybris/blob/master/hybris/egl/egl.c#L433

**Comment by bhush9** [comment]
Ah yeah.. I knew I would be missing something for sure :+1: will fix!

**Comment by bhush9** [comment]
I removed a useless two commits from branch and also modified egl.c

**Comment by krnlyng** [comment]
i think we should also add test_glesv3 which tests at least a simple functionality of glesv3

**Comment by bhush9** [comment]
I unfortunately have no idea on how to write up test, I tried looking at test_glesv2, but that test is broken for me so.. mm..

**Comment by morphis** [comment]
> I unfortunately have no idea on how to write up test, I tried looking at test_glesv2, but that test is broken for me so.. mm..

We should definitely have a test for this. Just use some GLESv3 only functionality for rendering. What makes test_glesv2 break for you?

**Comment by bhush9** [comment]
https://github.com/libhybris/libhybris/blob/master/hybris/tests/test_glesv2.c#L104 It crashes me on this line.. eglGetDisplay basically ends up in some kind of gralloc code IIRC and crashes.. I can give proper backtrace later evening

**Comment by krnlyng** [comment]
which EGL_PLATFORM are you using?

**Comment by bhush9** [comment]
I tried with almost all, null, fbdev, hwcomposer, wayland.. :D

**Comment by bhush9** [comment]
Ah actually on 2nd thought, it was test_egl which crashed in eglGetdisplay.. test_glesv2 crashed in eglCreateWindowSurface, see this comment : https://github.com/Halium/projectmanagement/issues/10#issuecomment-305996198

**Comment by kszaq** [comment]
@bhush9 Perhaps you can also remove these lines: https://github.com/libhybris/libhybris/blob/master/hybris/glesv2/glesv2.c#L683-L690

**Comment by krnlyng** [comment]
@kszaq those are probably still required for GLESv2 only clients :)

**Comment by krnlyng** [comment]
@Ntemis that sounds good! since you are using this successfully, would it be easy for you to add a test that confirms the functionality?

**Comment by Ntemis** [comment]
http://nightly.builds.lakka.tv/Lakka-2.1-dev_RetroArch_1.7.1/S912.arm/
You can try N64/PSX/PSP cores

**Comment by Ntemis** [comment]
fyi this just made it into batocera too for S912 and confirmed to work fine there too
https://batocera-linux.xorhub.com/
Image for test is here
moz-extension://8466f3c6-ab18-4956-9fdf-f934fb21423a/mega/secure.html#!AbhwBLZI!6dTDTbNkIDnGdfB-JdLyQfW0wJ8ybzqY0mNvo05JS6c

**Comment by kszaq** [comment]
@Ntemis This is about creating a test similar to https://github.com/libhybris/libhybris/blob/master/hybris/tests/test_glesv2.c

**Comment by Ntemis** [comment]
@kszaq No this is using OGLES V3 in real images(os)

**Comment by krnlyng** [comment]
@Ntemis all that is missing from this pull request is a test like @kszaq mentioned. that is why it isn't merged yet.

**Comment by suzuke** [comment]
@Ntemis 
To be clear, about the batocera.linux S912 image that i made, it runs emulationstation with opengles v2 not v3.
(please see https://github.com/suzuke/batocera.linux/blob/s912-porting/board/recalbox/s912/fsoverlay/etc/init.d/S31emulationstation line17)
I can't confirm that opengles v3 is really working for me.

**Comment by Ntemis** [comment]
@suzuke did it here
https://gist.github.com/suzuke/f85101b9ec8b4a93ac32cc8bddec97a0

**Comment by suzuke** [comment]
i have created a test similar to test_glesv2
with my patch https://gist.github.com/suzuke/f85101b9ec8b4a93ac32cc8bddec97a0
it works on S912, but I am not sure that it is the correct way to test glesv3.

**Comment by krnlyng** [comment]
@Ntemis that seems to be a copy of the test_glesv2 test with the context version changed from 2 to 3, not necessarily a GLESv3 specific test.

**Comment by Ntemis** [comment]
All i can say is the obvious , i am using this patch with
-SUBDIRS += egl glesv1 glesv2 glesv3 ui sf input camera vibrator media wifi
+SUBDIRS += egl glesv1 glesv2 glesv3
And works.

**Comment by krnlyng** [comment]
@Ntemis doesn't seem much is using libGLESv3.so in that image you mentioned:

$ cd ~/coding/Lakka-S912.arm-2.1-devel-canary-dc045e0/target
$ sudo mount SYSTEM ~/system



$ grep -r GLESv3 ~/system
grep: ~/system/etc/shadow: Permission denied
Binary file ~/system/system/lib/libGLESv3.so matches
grep: ~/system/usr/lib/dbus/dbus-daemon-launch-helper: Permission denied
Binary file ~/system/usr/lib/libEGL.so.1.0.0 matches
Binary file ~/system/usr/lib/libGLESv3.so.3.0.0 matches



$ grep -r GLESv2 ~/system
grep: ~/system/etc/shadow: Permission denied
Binary file ~/system/system/lib/libEGL.so matches
Binary file ~/system/system/lib/libGLESv2.so matches
Binary file ~/system/system/lib/libgui.so matches
Binary file ~/system/usr/bin/retroarch matches
Binary file ~/system/usr/bin/test_glesv2 matches
grep: ~/system/usr/lib/dbus/dbus-daemon-launch-helper: Permission denied
Binary file ~/system/usr/lib/libEGL.so.1.0.0 matches
Binary file ~/system/usr/lib/libGLESv2.so.2.0.0 matches
Binary file ~/system/usr/lib/libretro/mupen64plus_libretro.so matches
Binary file ~/system/usr/lib/libretro/parallel_n64_libretro.so matches
Binary file ~/system/usr/lib/libretro/ppsspp_libretro.so matches
Binary file ~/system/usr/lib/libretro/reicast_libretro.so matches



independant of if it is using it or not, libhybris should have a test_glesv3 regardless.

**Comment by krnlyng** [comment]
@bhush9 can you rebase this?

i'll check if i can come up with a test.

**Comment by Ntemis** [comment]
since am using it please ping me if possible when is done so i can rebase and update S912 for lakka

**Comment by bhush9** [comment]
@krnlyng Rebased the pull request to master.

**Comment by bhush9** [comment]
I wonder if with this https://github.com/libhybris/libhybris/pull/316 should be reverted?

**Comment by Ntemis** [comment]
omg why hardcode that? hope it gets reverted asap

**Comment by krnlyng** [comment]
@bhush9 i am not sure tbh. maybe we still want to force glesv2 for apps that link against glesv2 directly and only allow glesv3 for those who actually link against glesv3.

**Comment by krnlyng** [comment]
@bhush9 i think you could copy test_glesv2 and test a Instanced function, e.g. glDrawArraysInstanced by using gl_InstanceID in the shader

**Comment by kszaq** [comment]
@bhush9 Please patch `hybris/include/Makefile.am` to install GLES3 headers: https://github.com/kszaq/libhybris/commit/9e25d24a552bdb998b35cc26319414f2ab827a40

**Comment by krnlyng** [comment]
This has been merged in a different PR. Thanks for the work!

**Pull request closed without merging**
