### PR TITLE
N linker + fixes

### PR DESCRIPTION
**Pull request by krnlyng**
This is the nougat linker for libhybris.
Some hwcomposer implementations (and other libraries) use the new android libdl namespaces, therefore we need a new linker for newer ports.

### CODE REVIEW

**Comment by krnlyng** [comment]
I have added two more patches from @sledges which makes it easier to detect which linker to build and which quirks to use. Also the mm linker is not considered experimental anymore but simply enabled when the android version is 6 or higher.

**Comment by sledges** [comment]
Those two patches are WIP, do not merge this in yet.

**Comment by krnlyng** [comment]
Tested extensively, removing WIP status. Let me know if changes are necessary.

**Comment by sledges** [comment]
LGTM from me

**Comment by krnlyng** [comment]
adding a commit to adapt to the upcoming /odm partition paths. i.e. allow libraries to be loaded from /odm.

**Comment by morphis** [comment]
LGTM

**Pull request merged**
